[package]
name = "hack"
version = "0.1.0"
authors = ["Po Chen <chenpaul914@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
